### ISSUE TITLE
Sistema de Salas Temporárias

### ISSUE THREAD

**Issue by DanielHe4rt** [he4rt/he4rt-bot-next#10]
Uma das coisas que eu vi num servidor chamado [English](https://discord.gg/english) foi a possibilidade salas de 2 ou 3 pessoas para quem quer conhecer novas pessoas e praticar inglês e queria entender a possibilidade de abstrair isso pra He4rt Developers.

![image](https://user-images.githubusercontent.com/6912596/206865869-b1b0feb9-54ac-4573-984f-8e06a18a5acb.png)

### Fluxo

Tipos de sala: conhecer-pessoas, trabalho, estudo. 

* Dado: Usuário timido/novato quer um espaço para conversar/transmitir tela ou conhecer pessoas
* Quando: Executar o comando `/sala {tipoSala} {qtdPessoas}`
* Então: criar sala e direcioná-lo para a mesma e mandar mensagem no chat principal caso seja sala para conhecer novas pessoas.

**Comment by Suburbanno** [comment]
Sensacional a ideia, +1

**Comment by Novout** [comment]
### Comando
- A sala seria deletada após um tempo X ou quando tiver ninguém no canal de voz?
- Usuários Não-Apresentados poderiam usar?

### tipoSala

Poderia ser algo do tipo:
- Only English ?
- Novato ?
- Mentoria ?
- Coworking ?

### qtdPessoas
- Teria limite?

**Comment by andressansantos** [comment]
muito boa, porque divide as pessoas para tornar fácil iniciar nesse caminho, poderia existir níveis
salas basic - 2 pessoas
salas interm - 5 pessoas

**Comment by DanielHe4rt** [comment]
## Comando

* Sala seria deletada após todos saírem da mesma.
* Apenas pessoas que apresentaram poderão utilizar.

## Tipos de Sala

* Todos os citados

## qtdPessoas 

* Creio que a ideia da Andressa pode ser melhor explorada e setarmos uma qtd especifica por uma label também.

**Comment by gitlherme** [comment]
Tipos de sala: conhecer-pessoas, trabalho, estudo.

Então: criar sala e direcioná-lo para a mesma e mandar mensagem no chat principal caso seja sala para conhecer novas pessoas.

Esse comando de direcionar para mandar mensagem no chat principal, seria o principal da sala ou o principal do servidor inteiro? Faria sentido mandar essa mensagem independente do tipo de sala, trocando o tipo da mensagem?

Por exemplo

Caso redirecione pra sala geral do servidor, ao usar o comando `/sala conhecer-pessoas 5`, a mensagem seria algo do tipo
"Pessoal, estou na sala X esperando pessoas pra trocar uma ideia e nos conhecermos".

Ao usar o comando `/sala estudo 5`, a mensagem seria algo do tipo
"Pessoal, estou na sala X esperando pessoas pra trocar estudarmos juntos".

Acredito que poderia ter uma tag de gaming, já que boa parte do servidor gosta de jogar, pode proporcionar uma imersão de entretenimento pro pessoal se conhecer melhor também, através não necessariamente de códigos, mas também dos jogos.

**Comment by Clerijr** [comment]
Ótima ideia! Mas acho muito mais útil para casos como dúvidas/reviews/mentorias. 

Caso o objetivo seja lidar com novatos/timidos conversando mais com a comunidade, apesar de ser uma ferramenta nova, acho que seria necessário algum tipo de motivação para que os mesmos procurem interação. 

Um exemplo seria alguem mais antigo na comunidade convidando novatos para conversar. Novamente, excelente idéia, só pontuei baseado no que vejo de outras pessoas que conheço. 

Já chamei pessoas para a he4rt que tinham a desculpa de 'não sabe o que fazer na comunidade'/'não tem o que agregar à comunidade', dificilmente alguém assim irá ter iniciativa de criar uma sala especificamente para interagir com o pessoal.

**Comment by Luisnadachi** [comment]
Uma dúvida que fiquei, caso a pessoa utilize o comando, ela vai ser conectada direto na sala? ou vai ter que entrar manualmente? Porque se for manualmente teria que criar um tempo que a sala seria apagada caso tiver vazia. Mas acho que as ideias do git + novout + andressa pode ser bem válido.
Um bot no discord que já faz isso so que não pelo chat, é o [Voice master](https://voicemaster.xyz), podemos ver um pouco sobre ele para basear algumas outras ideias.

**Comment by Sherlockzen** [comment]
Primeiramente, é uma ótima idéia! E acredito que seja útil para qualquer tipo de sala e motivos diferentes. Também vejo proveito no campo das lives, pra galera que faz live e quem ta começando pode criar uma salinha pequena pra interagir junto enquanto tá em live e tals.
Enfim, muito bom, os por menores e as regras acredito que vai se testando e adequando com o tempo, é muito válido experimentar na comu.
