### ISSUE TITLE
Sistema de Onboarding

### ISSUE THREAD

**Issue by danielhe4rt** [he4rt/he4rt-bot-next#12]
Na primeira versão do He4rtBot nós tinhamos essa mensagem de boas vindas (abaixo) e sim, vamos implementar isso de volta porém com mais detalhes e links para a pessoa se organizar (focado tudo em nosso Github).

```
🇧🇷 Bem-vindo a He4rt Developers!
▫️ Nós somos uma comunidade de auxilio a desenvolvedores e entusiastas com o intuito de proporcionar um networking entre os participantes desta comunidade;
▫️ É iniciante? Sem problemas, utilize os canais de ajuda e também visualize os tutoriais disponíveis em;
▫️ Nossa intuição é sempre ajudar, você pode tanto contribuir quanto pedir ajuda, não precisa ter vergonha somos todos uma comunidade, nos visamos sempre ajudar o próximo, tanto a conseguir emprego, quanto com duvidas, quanto com a amizade!

❗ Você pode se apresentar utilizando o comando `!apresentar`, com isto toda a comunidade pode ter noção de quem você é, lembre-se que é OPCIONAL se identificar realmente, nesta seção você poderá selecionar também as linguagens que você gostaria de aprender ou trabalhar, além do acesso ao chat de ajuda das mesmas.

----- novo -----
🚖 Caso você sinta que precise de ajuda para entender melhor nossa comunidade, você pode requisitar um tour com um de nossos membros voluntários utilizando o comando `/onboarding solicitar` e um de nossos membros te enviará uma mensagem assim que possível para te recepcionar.

❗ ATENÇÃO: esse comando deverá ser usado apenas para entender sobre o Discord e comunidade com o intuito te integrá-lo com mais facilidade. Se você deseja ajuda em algo técnico, busque ajuda no canal de #bate-papo ou nas salas especificas de cada linguagem.
```

Porém eu gostaria de propor um sistema de onboarding voluntário, onde membros dirão o horário de disponibilidade deles para recepcionar novos membros, onde ele terá a possibilidade de requisitar um membro mais antigo para apresentar a comunidade e apontar algumas referências pra pessoa não ficar perdida e se sentir acolhida a ponto de já chegar tendo uma referência!

### Fluxo

* Comando de Solicitação:    
   * Comando: `/onboarding voluntariar`
   * Descrição: envia uma mensagem pro membro que gostaria de receber outros membros na comunidade explicando o sistema todo e seus beneficios, assim, ele poderia confirmar baseado em um horário (manhã/tarde/noite) para ficar recebendo membros.
* Comando de Solicitação: 
   * Comando: `/onboarding solicitar`
   * Descrição: envia uma mensagem para pessoas envolvidas em onboarding dentro da nossa comunidade sinalizando um novo membro.
* Comando de Solicitação: 
   * Comando: `/onboarding finalizar`
   * Descrição: sinaliza a administração que o onboarding da pessoa foi finalizado e cria um registro que o membro voluntário concluiu o onboarding de um novo membro (podendo ser algo público ou não).

**Comment by kjkGustavo** [comment]
Uma ideia legal, seria o bot enviar no final um LINK do evento mais próximo da semana. 

`Ei, venha participar do nosso evento dia X também! Você está totalmente convidado. <link>`

**Comment by kjkGustavo** [comment]
Agora sobre o Onboarding, não acho que vale depender de pessoas voluntariadas. Hoje o tempo é a coisa mais preciosa para todas as pessoas. Até pq leva um tempo, feeling para explicar e nem sempre as pessoas se dão bem logo de primeira.

Acho mais legal, ter um comando de onboarding e deixar todas as info da comunidade. Se o usuário ainda tiver dúvidas, ele marca uma @role para isso.

**Comment by yayaflc** [comment]
Gostei da ideia inicial do Onboarding mas não sei se na prática possa dar certo... Na minha visão não é todo mundo que consegue lidar/ter paciência com qualquer tipo de pessoa para recepcioná-la e que no final seja uma boa experiencia para ambos. Acho válido implementarmos para testes e ver como funcionará na prática, já que dependerá de pessoas para o sistema rodar, mas caso seja algo que não dê retorno, a ideia do Gustavo de uma @role é interessante!

**Comment by yayaflc** [comment]
Acho legal também enviar o link na mensagem de boas-vindas de uma doc (que já está em andamento rs) sobre a comunidade, com tudo bem explicadinho, para que membros novos possam ler e entender antes, sem chamar um voluntário para lhe ajudar com coisas que já estariam pré-escritas na doc.

**Comment by DanielHe4rt** [comment]
Creio que podemos levantar em primeiro momento essa possibilidade. O problema de usar role é marcar MUITA GENTE e muita gente ir falar com a pessoa. 

Não sei como seria essa comunicação, mas já seria um adianto onde a @ROLE tivesse uma sala e toda vez q alguém usasse onboarding, o bot avisasse nessa sala e a pessoa q recepcionar falar entre elas mesmas.

Sendo bem sincero eu não sei como resolver isso de um jeito que não envolva uma pessoa lá.

**Comment by diogoodev** [comment]
Talvez a ideia do @ROLE acabe sendo mais funcional, mas poderia misturar ela com a ideia inicial.

Comando de Solicitação:
Comando: /onboarding voluntariar
Descrição: envia uma mensagem pro membro que gostaria de receber outros membros na comunidade explicando o sistema todo e seus beneficios, assim, ele poderia confirmar baseado em um horário (manhã/tarde/noite) e dia da semana (seg, ter, qua, qui, sex, sab, dom) para ficar recebendo membros.
omando de Solicitação:
Comando: /onboarding solicitar
Descrição: envia uma mensagem para pessoas envolvidas em onboarding dentro da nossa comunidade sinalizando um novo membro. 

Aqui o membro que entrou escolhe o dia e o turno que ser apresentado a comunidade.
Dai reuni todos os membros que solicitaram pro mesmo dia e turno e notifica o voluntariado para fazer a apresentação para a galera no @role.

Comando de Solicitação:
Comando: /onboarding finalizar
Descrição: sinaliza a administração que o onboarding da pessoa foi finalizado e cria um registro que o membro voluntário concluiu o onboarding de um novo membro (podendo ser algo público ou não).

Acho que poderia ter um sistema de notas, para que as pessoas avaliassem a apresentação da comunidade e do voluntariado, assim ia dá para valorizar a galera que tivesse mandando bem.
Fazendo dessa forma possivelmente iria demandar menos voluntários. E não ficariam sobrecarregados por ser uma apresentação em grupo.
