### ISSUE TITLE
Sugestão: Sistema de Reputação

### ISSUE THREAD

**Issue by Novout** [he4rt/he4rt-bot-next#19]
O Sistema de Reputação teria como propósito geral incentivar as pessoas a ajudarem dentro do servidor e serem destacadas pela ajuda. Outros sistemas no servidor como o *Onboarding* e os *Feedbacks* poderiam funcionar em conjunto com a reputação.

### O que seria?

- Cada usuário teria um campo adicional em sua conta (*reputation*) que seria um número inteiro, iniciando em 0 e requerido que poderia ser negativo ou positivo e alteraria dependendo das atitudes do membro dentro do servidor.
- Valores fora da curva (-5 e 10, por exemplo) alertaria a administração para punir/recompensar o membro em questão
- Este sistema implicaria *tags* de recompensa (*beginner/intermediate/advanced/supreme/he4rt*) assim como outros sistemas (experiência / perfil).

### Vantagens

- Poderia incentivar os membros a utilizarem com mais afinco o `forum-de-ajuda`.
-  Poderia incentivar mais interações entre membros novos e antigos.

### Problemáticas

- Um membro poderia se sentir mal por estar com um reputação ruim (o *reputation* não necessariamente seria um dado público).
- Recompensar somente amigos (panela).

**Comment by Luisnadachi** [comment]
Acho uma boa esse sistema de reputação, mas sobre os pontos trazidos tenho uma:

- Teria algum limite de reputação para os usuários, ou seria algo "ilimitado" que o usuário possa ter?

Sobre os pontos levantados, pensei em algumas coisas:

- Poderia colocar um limite de reputação que um usuário poderia usar no server que resetasse a cada mês, por exemplo: Usuários podem recomendar outro usuários 3 vezes. Isso ia de certa forma controlar "farm" de recomendação e deixa algo mais "raro" uma recomendação.
- Para evitar a questão que você trouxe sobre as pessoas visualizarem os números de reputação, poderia criar labels baseadas nos números: Reputação baixa, reputação neutra, reputação mediana, reputação boa, e só o próprio usuário e a administração teria acesso aos números.
- Poderia utilizar o mesmo sistema antigo de recomendação no ponto de uma pessoa só conseguir recomendar uma mesma pessoa somente uma vez.
- E para evitar ainda mais o esquema de recomendação entre panelas, poderia colocar algum campo de motivo para qual está recomendando essa pessoa, com isso a administração teria acesso.

**Comment by Novout** [comment]
Resolvido. Agora o comando /avaliar aplica +1 rep ou -1 rep caso seja aprovado por um administrador.
