### ISSUE TITLE
Opções adicionais para o comando /sala

### ISSUE THREAD

**Issue by Novout** [he4rt/he4rt-bot-next#32]
A ideia disto seria fomentar a utilização do comando `/sala` para outros estilos de canais de voz, sendo uma alternativa direta para os canais de voz já existentes no servidor.

- Estudando ?
- Joguinhos?
- Conversando ?

**Comment by 1pride** [comment]
Não acho que o conversando seria uma boa, pois já existe 2, e as pessoas em si não entravam porque não se sentiam confortáveis e com isso criou-se o Novas-Amizades(criado pelo bot) justamente para isso, o Estudando até vejo sentido porque às vezes o canal fixo já está tendo um movimento que pode atrapalhar e por fim o Joguinhos não acho que seja a boa, pois o foco sempre foi focar a galera e o canal atual é relativamente pouco usado, é quase sempre as mesmas pessoas.

**Comment by Luisnadachi** [comment]
Eu concordo com os pontos do Pride, acho interessante poder criar um canal de estudando mas conversando já tem 2 fixos somado com os "novas amizades" e joguinhos é meio foda pq a comunidade não é focada nisso, no geral temos um ali como forma de escape pra galera que não ta estudando e se distraindo um pouco.

**Comment by yayaflc** [comment]
**Joguinhos** e **Conversando** acredito que não seria necessidade, como comentaram acima. Um não possui tanto movimento e não é o foco da comunidade e o outro já possui 2 opções disponiveis, que o foco é juntar a galera toda ali. Já a categoria **Estudando** eu acho interessante para pessoas que queiram estudar juntas limitando a quantidade de pessoas na sala ou fazer um grupo de estudos, tendo em vista que a sala padrão **Estudando** sempre ficam pessoas ali apenas mutadas. Outro ponto é que as categorias disponiveis sem serem sociais no comando `/sala` são apenas **Mentoria** e **Trabalhando**, o que acaba limitando as pessoas que não se encaixam nesses dois.

**Comment by DanielHe4rt** [comment]
COncordo com os pontos acima. Apenas uma adição de `Estudando` já seria bem interessante pra gente.
