### ISSUE TITLE
Possibilidades para info "Estado" de Usuário

### ISSUE THREAD

**Issue by DanielHe4rt** [he4rt/he4rt-bot-next#35]
Recentemente foi implementado na API uma funcionalidade para colher o `Estado (UF)` do usuário. Porém precisamos abstrair um pouco mais essa ideia antes de evangelizar isso pros nossos membros.

Duas coisas que eu vejo suma importância pra termos esses dados é:

* Para as pessoas de fora verem de algum jeito de onde nossos membros são (mapa de calor possivelmente) na nossa landing page;
* Para nós como administração sabermos onde trazer novos eventos baseado em qtd de pessoas aderindo.

> Pretendemos levar eventos para todos os estados, mas inicialmente precisamos ver onde é mais viável.

A ideia aqui é entender como nós podemos aproveitar esses dados e beneficiar nossa comunidade. O que vocês acham?

**Comment by Luisnadachi** [comment]
Acho uma boa, até mesmo no futuro podemos entrar em contato com as pessoas de X estado quando ocorrer um evento avisado pra ela sobre isso, mas caso vá pra frente esse ponto do UF, não seria uma boa colocar **pais** também? Porque temos muitos devs que moram lá fora.

**Comment by louzada01** [comment]
Faz muito sentido, ainda mais pensando em questões como engajamento de novos membros. 

Podemos ter um cadastro de usuarios, de fato, pois hoje o que temos como base de dados é o Discord, correto ? 

Talvez integrar isso com uma planilha de forma simples, utilizando o ID do discord como chave assim podemos ter essa base de dados.

**Comment by yayaflc** [comment]
Acho a ideia muito interessante. Acredito que quanto mais informações conseguirmos coletar desse gênero, melhor para a criação de métricas, assim como coleta de gênero e etnia, com esses dados podemos criar nossos projetos em torno de uma melhor igualaria. Um possível mapa de calor na landing page também é legal para que todos possam ter noção sobre a expansão da He4rt no Brasil inteirinho!

**Deixo aqui uma ideia:** coletar a info de `Cidade` (não necessáriamente para deixar público) para que assim pudessemos implementar um He4rtPub (inspirada no PHPSP Pub), já que muitos membros moram na mesma cidade mas não possuem oportunidade de se encontrarem (por falta de iniciativa) ou para aqueles que não possuem condições de viajar para outra cidade/estado para encontrar a comunidade e criar laços.

**Comment by yayaflc** [comment]
Acho a ideia muito interessante. Acredito que quanto mais informações conseguirmos coletar desse gênero, melhor para a criação de métricas, assim como coleta de gênero e etnia, com esses dados podemos criar nossos projetos em torno de uma melhor igualaria. Um possível mapa de calor na landing page também é legal para que todos possam ter noção sobre a **expansão da He4rt no Brasil inteirinho!**

Deixo aqui uma ideia: coletar a info de `Cidade` (não necessáriamente para deixar público) para que assim pudessemos implementar um **He4rtPub** (inspirada no PHPSP Pub), já que muitos membros moram na mesma cidade mas não possuem oportunidade de se encontrarem (por falta de iniciativa) ou para aqueles que não possuem condições de viajar para outra cidade/estado para encontrar a comunidade e criar laços.

**Comment by Novout** [comment]
https://github.com/he4rt/he4rt-bot-next/pull/37
