### ISSUE TITLE
Sugestão: Forma de parar apresentação do bot

### ISSUE THREAD

**Issue by P0sseid0n** [he4rt/he4rt-bot-next#42]
É preciso uma forma de parar a apresentação para o bot não ficar em loop floodando na DM

**Comment by DanielHe4rt** [comment]
Consegue mostrar o que está acontecendo? Eu não conheço muito bem o fluxo, mas se tiver um passo a passo pra fazer seria bacana.

**Comment by P0sseid0n** [comment]
No código ou na pratica ?
Na pratica antes o bot iniciava a apresentação e não parava enquanto não respondesse todas as perguntas.
A feature adiciona o comando `/parar` que em qualquer pergunta do bot para a apresentação. 
Também se chegar ao final 3 vezes com o valor de uma pergunta invalido o bot para a apresentação.

**Comment by fernanduandrade** [comment]
Acredito que não é possível criar um comando pois a apresentação ocorre na DM e os únicos comandos disponíveis são os built-in, talvez se criar uma palavra reservada e.g **parar** e adicionar na verificação de validação de resposta, se a resposta do usuário foi **parar** então parar o fluxo

**Comment by P0sseid0n** [comment]
Fiz um PR #43 que resolve isso, que adiciona adiciona o comando `/parar`
