### ISSUE TITLE
Atualizações de avatares via API

### ISSUE THREAD

**Issue by DanielHe4rt** [he4rt/he4rt-bot-next#44]
Recentemente vimos a necessidade de guardar o avatar do usuário do Discord junto com algumas outras informações e vejo que possivelmente há a necessidade de atualizar isso periodicamente.

Talvez podemos fazer algo visando o front-end junto com cache (Redis) ou eu posso fazer um cron no back-end utilizando a mesma forma.

Onde seria usado a imagem? No perfil de usuário da He4rt.

**Comment by Novout** [comment]
Cronjob no back-end acho válido pois é algo que vai ser utilizado em contextos que não tem correlação direta com o cliente do bot do discord (he4rt-landing, por exemplo).

**Comment by Tsugami** [comment]
O Discord envia um evento gateway quando o usuário troca de avatar, da pra usar ele pra manter o cache atualizado, além do cronjob.

https://discord.com/developers/docs/topics/gateway-events#guild-member-update

O `GUILD_MEMBERS` já ativado https://github.com/he4rt/he4rt-bot-next/blob/main/src/main.ts#L13

**Comment by Novout** [comment]
Atualmente o discord-bot-api já está enviando os avatares.
