### ISSUE TITLE
Global.d.ts

### ISSUE THREAD

**Issue by Joabesv** [he4rt/he4rt-bot-next#45]
é realmente necessário setar as envs pelos arquivo de modulos typescript?
nao seria melhor usar  `as type` no código?

**Comment by Novout** [comment]
Por que `não` setar os tipos globais do `process.env` sendo que ele infere o tipo no tree-sitter (consequentemente dispensando o uso do `as`)?

**Comment by Joabesv** [comment]
Nao entendi bem a parte do `tree-sitter`
mas acho q setar os tipos de maneira global é "passar por cima" do q é definido

**Comment by Joabesv** [comment]
Vi as necessidades atuando em algo parecido em trampos e projetos pessoais
pra nao poluir as issues, vou fechar essa aqui.
