### ISSUE TITLE
Usuário consegue colocar qualquer link como github ou linkedin.

### ISSUE THREAD

**Issue by joaooliveira247** [he4rt/he4rt-bot-next#46]
Usuario pode enviar qualquer link como github ou linkedin, esse link está sendo passado para o [backend](https://github.com/he4rt/he4rt-bot-api), portando quando clicko no perfil de alguem ele pode me redirecionar para qualquer lugar.

**Comment by Novout** [comment]
O problema é que há casos que o usuário não tem o link e escreve qualquer coisa no lugar. Como faríamos para resolver esse caso se o bot obrigasse a passar o url correto?

**Comment by joaooliveira247** [comment]
se tiver algo vc passa pela verificaçã, se n for valido vc deixa None e raisa uma exception na cara do user.

**Comment by DanielHe4rt** [comment]
Vou fixar isso já!

**Comment by DanielHe4rt** [comment]
Resolvido.
https://github.com/he4rt/he4rt-bot-api/commit/42ee3e61b7010b07da6b3f23fa85ea7f75d336b3
