### ISSUE TITLE
Alterar o tamanho da sala temporária após a criação.

### ISSUE THREAD

**Issue by henri1i** [he4rt/he4rt-bot-next#47]
Atualmente, quando uma sala temporária é criada, e chega no seu limite, para novas pessoas entrarem, é necessária a criação de uma nova sala com o tamanho correto.

Exêmplo atual: 
É criada uma Sala de trabalho 2/2, mas um outro colega pede para entrar. Uma nova sala com limite de 3 pessoas precisa ser criada.

Exêmplo solução:
No chat da sala temporária:  `/tamanho-sala 3`

**Comment by Novout** [comment]
Feito. Estará disponível na `2.7.0`

![h](https://user-images.githubusercontent.com/41403842/211877658-e4601dd3-392c-4997-b848-4e804b13a60c.png)
