### ISSUE TITLE
Bot floodando mensagem privado no /apresentar

### ISSUE THREAD

**Issue by Tsugami** [he4rt/he4rt-bot-next#50]
Usei o `/apresentar` pra testar como está, mas não terminei o formulário e agora ele está flooodando meu privado. [Vídeo](https://cdn.discordapp.com/attachments/711318231087841413/1062936577376002058/2023-01-12_00-28-04.mkv)

**Comment by Novout** [comment]
Ele flooda por ser recursivo mas na `develop` já está com isso arrumado (https://github.com/he4rt/he4rt-bot-next/issues/42).
