### ISSUE TITLE
Criação de salas temporárias customizáveis 

### ISSUE THREAD

**Issue by SamucaDev** [he4rt/he4rt-bot-next#52]
## Criação de salas temporárias customizáveis
 
Quero levantar uma discussão a respeito de uma ideia.

Hoje temos o sistema de criação de salas temporárias, seria interessante a opção de o que estamos estudando.

Ex: Estudando: Rust 

Podemos deixar um select com uma lista de linguagens, na ausência (nao selecao) podemos deixar como já é hoje.

![Captura de tela de 2023-01-16 14-27-40](https://user-images.githubusercontent.com/51060285/212736369-a0b9ec5e-2167-49e2-957b-ff8f7ef66a43.png)

Um problema do discord é que nomes grandes ficam com "..." porém quando abrimos o chat ou entramos no canal temos acesso ao título completo. 

Ganhos com isso:

- O canal será mais objetivo, ex se eu vejo uma pessoa estudando React, vou entrar pois é uma stack que eu gosto. E a pessoa ao abrir um sala Estudando: React, esta convidando, mesmo que indiretamente, pessoas para se juntar a este estudo.

**Comment by yayaflc** [comment]
Gostei muito da ideia! Assim podemos identificar mais fácil sobre o que está rolando na sala sem precisarmos entrar.

**Comment by venturacodes** [comment]
Gostei bastante da idéia também. Um adendo: Ao invés de select permitir escrever o que está estudando limitando o número de caracteres do input.

ex: 
Quero estudar Domain Driven Design, contudo o título é grande e entraria na questão dos ... . Caso o input seja limitado, quem está cadastrando pode entender que deve colocar um título menor, nesse caso um possível seria DDD.

Ganhos com isso:

- Mais flexibilidade para a pessoa descrever, já que as opções no select serão fixas e caso meu estudo não esteja no select eu vou acabar deixando ele genérico ou mesmo sem titulo.

Outra idéia de customização também seria para os canais estudando, deixar o estudando como default, mas caso a pessoa preencha um valor, mantemos o icone do livro e o título. Abaixo coloquei dois formatos possíveis que podem ser interessantes:

Ex: 
![image](https://user-images.githubusercontent.com/2498402/213255658-69a14276-cc17-409d-b8c2-08b609c1e7f9.png)

O segundo com estudando no final poderia ajudar com a barreira dos ... caso o tamanho do título seja muito grande. Assim limitando menos o input e facilitando para quem for criar a sala.

**Comment by Novout** [comment]
Feito. https://github.com/he4rt/he4rt-bot-next/pull/49/commits/0b223f08133e6173230a5efe4fe2f114420a29ab

![image](https://user-images.githubusercontent.com/41403842/213555577-53cf2115-e737-4fc9-beb5-00decb0b569d.png)
![image](https://user-images.githubusercontent.com/41403842/213555706-922d6d81-1011-4a5f-8811-49f0a3149d21.png)
