### ISSUE TITLE
Comando para parar DM do bot

### ISSUE THREAD

**Issue by yayaflc** [he4rt/he4rt-bot-next#53]
Após experiência própria e alguns relatos de outros membros, quando acionado o comando o `/apresentar` por engano, o bot spamma as perguntas na DM sem parar, apenas para se refazemos todo o processo de perguntas, o que pode ser desconfortável principalmente para aqueles que não possuem afinidade com o  Discord e Bots e que não sabem sobre essa solução.

A solução para isso seria um botão explícito em todo o processo para **cancelar** a apresentação.

**Comment by Novout** [comment]
Feito: https://github.com/he4rt/he4rt-bot-next/pull/49/commits/4929cea3b78688b2b435b5200a619855300513cf
