### ISSUE TITLE
Comando /watch e /watchlist

### ISSUE THREAD

**Issue by yayaflc** [he4rt/he4rt-bot-next#54]
Muitos membros acabam tendo atitudes em chamadas de voz e bate-papo um pouco desconfortável a ponto de não precisar de uma punição logo de primeira, havendo a necessidade de que a Equipe de Administração/Moderação possam ficar de olho nesses pessoas específicas, para que estejam de prontidão caso ocorra algo.

Mas como identificar quem faz parte desse grupo de pessoas?

Após observar meu colega de equipe utilizando uma palavra chave no canal de #punishments-and-mods para sinalizar essas pessoas, pensei na seguinte solução: 

-  `/watch [ID] [motivo]` : para adicionar o usuário na lista de observação.
- `/watchlist` : para acessar a lista de usuários que estão sendo observados.

> Vale lembrar que é um comando que apenas a Equipe de Moderação e Administração possuem acesso.

Dessa maneira, moderadores ativos e não ativos poderão ficar ciente sobre esses membros, sem que a mensagem no chat passe batido e se perca.

**Comment by DanielHe4rt** [comment]
Interessante. Podemos colocar pra V2 que vai sair, por agora não temos como ou porquê implementar isso sendo que vai mudar o sistema todo.

Porém já vou colocar como algo novo pra essa próxima versão. Achei bem interessante a galera da própria comunidade alertando "pequenas atitudes".

**Comment by Novout** [comment]
![image](https://github.com/he4rt/he4rt-bot-next/assets/41403842/ff95c04b-27e2-48fc-be37-f1e5d217c5f0)

Feito. Estará disponível na `v2.9.0`
