### ISSUE TITLE
Sugestão: remover reação do bot ao iniciar uma thread no #sugestões

### ISSUE THREAD

**Issue by fernanduandrade** [he4rt/he4rt-bot-next#57]
Remover reação do bot ao iniciar uma thread no canal de #sugestões 
<img width="417" alt="image" src="https://user-images.githubusercontent.com/58053397/215139224-eca03957-e44d-46a3-bb17-56bcc6786e44.png">

**Comment by Novout** [comment]
Resolvido. Estará disponível na `v.2.9.0`
