### ISSUE TITLE
Sugestão: Remover o limite obrigatório de salas personalizadas.

### ISSUE THREAD

**Issue by henri1i** [he4rt/he4rt-bot-next#61]
Entendo permitir a adição de um limite às salas personalizadas, mas para mim, obrigar essa limitação não faz o menor sentido.

**Comment by Gstxxx** [comment]
jóia.

**Comment by joaocstro** [comment]
Também não vejo sentido nessa limitação. A quantidade máxima de membros na sala deveria ser responsabilidade de quem a criou, e não um limite obrigatório que atualmente só dificulta a interação entre as pessoas. É extremamente comum que um usuário tenha que ser movido para participar da conversa.
