### ISSUE TITLE
Ajuste na mensagem do apresentar

### ISSUE THREAD

**Issue by Luisnadachi** [he4rt/he4rt-bot-next#88]
Percebi que muita gente está tendo a problemática na hora de fazer o apresentar que é ao inves de digitar somente um número por vez, estão digitando todos os números e com isso o apresentar não funcionando, talvez como solução prévia seria adicionar uma mensagem avisando as pessoas que é para colocar somente um número por vez.  

![langs](https://github.com/he4rt/he4rt-bot-next/assets/51420622/167c35c9-e83b-430e-bee2-875b6c285e18)

**Comment by Novout** [comment]
Resolvido.
